FROM confluentinc/cp-kafka:latest

# Environment variables for Kafka
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
ENV KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

CMD ["sh", "-c", "exec /etc/confluent/docker/run"]
