# Use Python as the base image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Expose the Flask API port
EXPOSE 5500

# Run the Flask app
CMD ["python", "web_ui/app.py"]
